### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [benibela/videlibri#13]
https://gitlab.com/fdroid/fdroiddata/-/jobs/7170087069

Could you please take a look? Thanks!

**Comment by benibela** [comment]
>/usr/bin/install -c -m 755 ppcx64 /home/vagrant/build/srclib/fpc/install/lib/fpc/3.2.2/ppcx64
...
>/home/vagrant/build/srclib/fpc/install/lib/fpc/3.2.0/ppcx64 not found.  

has it updated the compiler version?

**Comment by linsui** [comment]
Wow, so we are using a moving branch. I'll pin it to a tag.

**Comment by benibela** [comment]
3.2.2 does not work, it causes crashes

**Comment by linsui** [comment]
Hmm, then I'll pin it to a commit.

**Comment by linsui** [comment]
Fixed.
