### ISSUE TITLE
track watch list / bookmark list

### ISSUE THREAD

**Issue by hilbert-ralf** [benibela/videlibri#2]
Is there any plan to also cover books I have marked for getting later?
For my library its possible to create such a list (in the web ui) but unfortunately it's hard to keep track then a specific book gets available.
It would be great to have this list within videlibri sorted by date it gets available in my configured favorite library.

**Comment by benibela** [comment]
So far I had no plans for that

Currently the only way is to copy the bookmarks in the history list as if the book had been borrowed and already returned.

But there is no way to see if a book has become available in VideLibri. It is also difficult to implement. And that availability check would need to be implemented for every catalogue separately

**Comment by hilbert-ralf** [comment]
I see, thank you for answering anyway. =)
