### ISSUE TITLE
versionCode not increased?

### ISSUE THREAD

**Issue by IzzySoft** [benibela/videlibri#5]
The APK attached to v2.610 has the same `versionCode` as the one at v2.600: `2600`. Maybe you forgot to increase it? That will also have the F-Droid build fail then. Can you please check (and fix)?

**Comment by benibela** [comment]
The tag was on the wrong commit

Often I tag it and then increase the number in the next commit

**Comment by IzzySoft** [comment]
> Often I tag it and then increase the number in the next commit

That will have 2 nasty side-effects:

* there won't be an F-Droid build: as a build with the given `versionCode` already exists, CheckUpdate won't even consider the new tag
* in my repo, the APK would simply replace the previous one – not only making the previous one unavailable in my repo, but neither will the users receive the update as their clients do not consider it being such, since the `versionCode` didn't change

So better make it your always-process to first adjust `versionName`/`versionCode` and only tag once that is done.
