### ISSUE TITLE
duedate wrong for Stadtbibliothek Chemnitz

### ISSUE THREAD

**Issue by tribut** [benibela/videlibri#9]
When using `xidel` to query Stadtbibliothek Chemnitz as [suggested in the README](https://github.com/benibela/videlibri/blob/master/README.md#usage-as-library), the due date is wrong:

~~~bash
$ xidel -e '$username:="XXX",
          $password:="XXX",
          $server:="https://opac2.stadtbibliothek-chemnitz.de/webOPACClient/",
          $startparams:="?Login=opsb"
    ' --template-action connect,update-all  \
      --module mockvidelibri.xqm --xmlns videlibri=https://www.videlibri.de --dot-notation=on \
      --template-file data/libraries/templates/sisis/template \
      --output-format=json-wrapped \
      -s |
    jq -c 'last | .book[0] | [.title, .duedate]'
["Busy Bee","2023-04-25"]
~~~

This is how it looks on the web, the supposed due date is actually the date it was borrowed:

![Screenshot 2023-07-08 at 14-05-41 webOPAC](https://github.com/benibela/videlibri/assets/719105/d50ff9cd-d345-4d06-b37b-08dcaebcf6e2)

The table cell does not contain any additional markup in HTML:

~~~html
            <td>
             
             25.04.2023 - 21.07.2023<br>
             Zentralbibl.
            </td>
~~~

If you need any more information, please let me know.

**Comment by benibela** [comment]
I use a regular expression to get the dates `((\d{2}\.\d{2}\.\d{4}) *-)? *(\d{2}\.\d{2}\.\d{4}`: https://github.com/benibela/videlibri/blob/master/data/libraries/templates/sisis/loggedIn#L121C44-L121C94

Perhaps that is not as greedy as I thought it would be. Try removing the `?` from it

**Comment by benibela** [comment]
Oh, now I understand it

Just call Xidel wit the  `--deprecated-trim-nodes` option 

Alhough the regular expression does not match `   25.04.2023 - 21.07.2023` correctly, it works correctly for `25.04.2023 - 21.07.2023`.

**Comment by tribut** [comment]
Thanks, that did it!
